apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-deployment
  labels:
    app: books-service
  annotations:
    kubernetes.io/change-cause: "Update to v2 with improved search functionality"
    app.kubernetes.io/version: "v2"
    app.kubernetes.io/part-of: "avakart"
    app.kubernetes.io/managed-by: "kubectl"
spec:
  replicas: 5
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: books-service
  template:
    metadata:
      labels:
        app: books-service
        version: "v2"
    spec:
      containers:
      - name: books-service
        image: books-service:v2
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
        - name: STORAGE_SERVICE_URL
          value: "http://storage-service:8083"
        - name: ORDER_PROCESSOR_URL
          value: "http://order-processor:8082"
        - name: APP_VERSION
          value: "v2"
        - name: SCHEMA_VERSION
          value: "2"
        - name: ENABLE_NEW_SEARCH
          value: "true"  # This new feature might cause issues
        - name: SEARCH_TIMEOUT
          value: "1"     # Very short timeout that might cause problems
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 2
          failureThreshold: 3
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
