apiVersion: v1
kind: Secret
metadata:
  name: books-db-credentials
  labels:
    app: books-service
    app.kubernetes.io/part-of: avakart
type: Opaque
data:
  username: YWRtaW4=  # admin
  password: cGFzc3dvcmQxMjM=  # password123
