apiVersion: apps/v1beta1  # Deprecated, should use apps/v1
kind: Deployment
metadata:
  name: books-deployment
  labels:
    app: books-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: books-service
  template:
    metadata:
      labels:
        app: books-service
    spec:
      containers:
      - name: books-service
        image: avakart/books-service:v1
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "200m"
            memory: "128Mi"
        env:
        - name: DB_HOST
          value: "storage-service"
        - name: DB_PORT
          value: "27017"
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
