apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "order-processor.fullname" . }}
  labels:
    {{- include "order-processor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "order-processor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "order-processor.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        {{- range .Values.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        {{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: data
          mountPath: {{ .Values.persistence.mountPath }}
        {{- end }}
      {{- if .Values.storageAmbassador.enabled }}
      - name: storage-ambassador
        image: {{ .Values.storageAmbassador.image }}
        ports:
        - containerPort: {{ .Values.storageAmbassador.port }}
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
      {{- end }}
      volumes:
      {{- if .Values.storageAmbassador.enabled }}
      - name: nginx-config
        configMap:
          name: {{ include "order-processor.fullname" . }}-nginx-config
      {{- end }}
      {{- if .Values.persistence.enabled }}
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "order-processor.fullname" . }}-data
      {{- end }}
