version: '3.8'

services:
  frontend:
    build:
      context: ../..
      dockerfile: builds/dockerfiles/Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - bookstore-network

  backend:
    build:
      context: ../..
      dockerfile: builds/dockerfiles/Dockerfile.backend
    ports:
      - "8080:8080"
    depends_on:
      - storage
    environment:
      - STORAGE_SERVICE_URL=http://storage:8080
    networks:
      - bookstore-network

  order-processing:
    build:
      context: ../..
      dockerfile: builds/dockerfiles/Dockerfile.order-processing
    ports:
      - "8081:8080"
    depends_on:
      - storage
    environment:
      - STORAGE_SERVICE_URL=http://storage:8080
    networks:
      - bookstore-network

  storage:
    build:
      context: ../..
      dockerfile: builds/dockerfiles/Dockerfile.storage
    ports:
      - "8082:8080"
    networks:
      - bookstore-network

networks:
  bookstore-network:
    driver: bridge
