apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-deployment
  labels:
    app: books-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: books-service
  template:
    metadata:
      labels:
        app: books-service
    spec:
      containers:
      - name: books-service
        image: books-service:v1
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
