apiVersion: v1
kind: Pod
metadata:
  name: books-pod
spec:
  containers:
  - name: books-service
    image: books-service:v1
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    ports:
    - containerPort: 8081
