apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- pvc.yaml
- cronjob.yaml

commonLabels:
  app.kubernetes.io/name: order-processor
  app.kubernetes.io/part-of: bookstore-app

images:
- name: order-processor
  newName: order-processor
  newTag: latest
- name: nginx
  newName: nginx
  newTag: alpine
