apiVersion: v1
kind: Service
metadata:
  name: order-processor
  labels:
    app: order-processor
spec:
  selector:
    app: order-processor
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: http
  type: ClusterIP
