apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

commonLabels:
  app.kubernetes.io/name: books-service
  app.kubernetes.io/part-of: bookstore-app

images:
- name: books-service
  newName: books-service
  newTag: latest
