apiVersion: v1
kind: Service
metadata:
  name: books-service
  labels:
    app: books-service
spec:
  selector:
    app: books-service
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  type: ClusterIP
