apiVersion: v1
kind: LimitRange
metadata:
  name: avakart-limits
  namespace: avakart
spec:
  limits:
  - type: Container
    default:
      cpu: 200m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    max:
      cpu: 1
      memory: 1Gi
    min:
      cpu: 50m
      memory: 64Mi
