apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-processor-service-account
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/order-processor-role"
