apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-deployment
  labels:
    app: books-service
    tier: backend
  annotations:
    kubernetes.io/change-cause: "Initial deployment of books service v1.0.0"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0    # Zero downtime for backend service
  selector:
    matchLabels:
      app: books-service
  template:
    metadata:
      labels:
        app: books-service
        version: "1.0.0"
    spec:
      containers:
      - name: books-service
        image: books-service:1.0.0
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
        - name: STORAGE_SERVICE_URL
          value: "http://storage-service:8083"
        - name: ORDER_PROCESSOR_URL
          value: "http://order-processor:8082"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
      # Graceful shutdown period for backend connections
      terminationGracePeriodSeconds: 90
