apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processor-deployment
  labels:
    app: order-processor
    tier: backend
    component: processing    # Additional label for processing components
  annotations:
    kubernetes.io/change-cause: "Initial deployment of order processor v1.0.0"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0    # Ensure processing capacity during updates
  selector:
    matchLabels:
      app: order-processor
  template:
    metadata:
      labels:
        app: order-processor
        version: "1.0.0"
        component: processing
    spec:
      containers:
      - name: order-processor
        image: order-processor:1.0.0
        ports:
        - containerPort: 8082
        env:
        - name: PORT
          value: "8082"
        - name: STORAGE_SERVICE_URL
          value: "http://storage-service:8083"
      # Longer grace period for processing components
      terminationGracePeriodSeconds: 120    # Allow time for processing completion
