apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-deployment
  labels:
    app: storage-service
    tier: backend
    component: storage    # Identifies data storage component
  annotations:
    kubernetes.io/change-cause: "Initial deployment of storage service v1.0.0"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0    # Maintain data availability during updates
  selector:
    matchLabels:
      app: storage-service
  template:
    metadata:
      labels:
        app: storage-service
        version: "1.0.0"
        component: storage
    spec:
      containers:
      - name: storage-service
        image: storage-service:1.0.0
        ports:
        - containerPort: 8083
        env:
        - name: PORT
          value: "8083"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true    # Additional security for data service
      # Extended grace period for data consistency
      terminationGracePeriodSeconds: 180    # Allow time for connection draining
