apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/books
- ../../base/frontend
- ../../base/order-processor
- ../../base/storage

namespace: bookstore-prod

commonLabels:
  environment: prod

patches:
- target:
    kind: Deployment
    name: books-service
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: 200m
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 256Mi
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: 400m
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 512Mi
- target:
    kind: Deployment
    name: frontend
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: 200m
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 256Mi
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: 400m
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 512Mi
- target:
    kind: Deployment
    name: order-processor
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: 200m
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 256Mi
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: 400m
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 512Mi
- target:
    kind: Deployment
    name: storage-service
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: 200m
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 256Mi
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: 400m
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 512Mi

images:
- name: books-service
  newName: books-service
  newTag: prod
- name: frontend
  newName: frontend
  newTag: prod
- name: order-processor
  newName: order-processor
  newTag: prod
- name: storage-service
  newName: storage-service
  newTag: prod
