apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
    app.kubernetes.io/part-of: avakart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        app.kubernetes.io/part-of: avakart
    spec:
      serviceAccountName: frontend-service-account
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
      containers:
      - name: frontend
        image: frontend:latest
        securityContext:
          runAsNonRoot: true
          runAsUser: 101  # nginx user
          allowPrivilegeEscalation: false
          capabilities:
            add: ["NET_BIND_SERVICE"]
            drop: ["ALL"]
          readOnlyRootFilesystem: true
        env:
        - name: VITE_API_BASE_URL
          value: "http://books-service:8081"  # Default to internal k8s service name
        - name: LOG_LEVEL
          value: "info"
        - name: LOG_FORMAT
          value: "json"
        volumeMounts:
        - name: frontend-logs
          mountPath: /app/logs
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      - name: log-collector
        image: log-collector:v1
        volumeMounts:
        - name: frontend-logs
          mountPath: /var/log/app
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        command: ["/bin/sh", "-c"]
        args:
        - |
          tail -f /var/log/app/*.log | jq '.' || true
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
      volumes:
      - name: frontend-logs
        emptyDir: {}
      # Add a volume for temporary files needed by nginx
      - name: tmp-volume
        emptyDir: {}
