apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-deployment
  labels:
    app: books-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: books-service
  template:
    metadata:
      labels:
        app: books-service
    spec:
      containers:
      - name: books-service
        image: books-service:v1
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
        - name: STORAGE_SERVICE_URL
          value: "http://storage-service:8083"
        - name: ORDER_PROCESSOR_URL
          value: "http://order-processor-service:8082"
        # Using individual ConfigMap values as environment variables
        - name: PAGE_SIZE
          valueFrom:
            configMapKeyRef:
              name: books-service-config
              key: PAGE_SIZE
        - name: ENABLE_CACHE
          valueFrom:
            configMapKeyRef:
              name: books-service-config
              key: ENABLE_CACHE
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: books-service-config
              key: LOG_LEVEL
        - name: API_VERSION
          valueFrom:
            configMapKeyRef:
              name: books-service-config
              key: API_VERSION
        # Using individual Secret values as environment variables
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: books-db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: books-db-credentials
              key: password
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
