apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-proxy-config
  labels:
    app: order-processor
    app.kubernetes.io/part-of: avakart
data:
  default.conf: |
    server {
      listen 8083;
      location / {
        proxy_pass http://storage-service:8083;
      }
    }
