apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "storage.fullname" . }}
  labels:
    {{- include "storage.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "storage.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "storage.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        {{- range .Values.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        volumeMounts:
        {{- if .Values.volumes.logs.enabled }}
        - name: log-storage
          mountPath: {{ .Values.volumes.logs.mountPath }}
        {{- end }}
        {{- if .Values.volumes.cache.enabled }}
        - name: cache-storage
          mountPath: {{ .Values.volumes.cache.mountPath }}
        {{- end }}
        {{- if .Values.persistence.enabled }}
        - name: data
          mountPath: {{ .Values.persistence.mountPath }}
        {{- end }}
      {{- if .Values.logCollector.enabled }}
      - name: log-collector
        image: {{ .Values.logCollector.image }}
        command: {{ .Values.logCollector.command }}
        volumeMounts:
        - name: log-storage
          mountPath: /logs
      {{- end }}
      volumes:
      {{- if .Values.volumes.logs.enabled }}
      - name: log-storage
        {{- toYaml .Values.volumes.logs.emptyDir | nindent 8 }}
      {{- end }}
      {{- if .Values.volumes.cache.enabled }}
      - name: cache-storage
        emptyDir:
          {{- toYaml .Values.volumes.cache.emptyDir | nindent 10 }}
      {{- end }}
      {{- if .Values.persistence.enabled }}
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "storage.fullname" . }}-data
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
