apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
    app.kubernetes.io/part-of: avakart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        app.kubernetes.io/part-of: avakart
    spec:
      containers:
      - name: frontend
        image: frontend:latest
        env:
        - name: VITE_API_BASE_URL
          value: "http://books-service:8081"  # Default to internal k8s service name
        - name: LOG_LEVEL
          value: "info"
        - name: LOG_FORMAT
          value: "json"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: frontend-logs
          mountPath: /app/logs
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      - name: log-collector
        image: log-collector:v1
        volumeMounts:
        - name: frontend-logs
          mountPath: /var/log/app
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        command: ["/bin/sh", "-c"]
        args:
        - |
          tail -f /var/log/app/*.log | jq '.' || true
      volumes:
      - name: frontend-logs
        emptyDir: {}
