apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processor
  labels:
    app: order-processor
    app.kubernetes.io/part-of: avakart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-processor
  template:
    metadata:
      labels:
        app: order-processor
        app.kubernetes.io/part-of: avakart
    spec:
      containers:
      - name: order-processor
        image: order-processor:latest
        ports:
        - containerPort: 8082
        env:
        - name: PORT
          value: "8082"
        - name: STORAGE_SERVICE_URL
          value: "http://localhost:8083"  # Connect to local ambassador
        - name: LOG_LEVEL
          value: "info"
        - name: LOG_FORMAT
          value: "json"
        volumeMounts:
        - name: shared-logs
          mountPath: /app/logs
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 3
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
      - name: storage-ambassador
        image: nginx:alpine
        ports:
        - containerPort: 8083
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
      - name: log-collector
        image: log-collector:v1
        volumeMounts:
        - name: shared-logs
          mountPath: /var/log/app
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        command: ["/bin/sh", "-c"]
        args:
        - |
          tail -f /var/log/app/*.log | jq '.' || true
      volumes:
      - name: shared-logs
        emptyDir: {}
      - name: nginx-config
        configMap:
          name: storage-ambassador-config
