apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-deployment
  labels:
    app: storage-service
    tier: backend
    component: storage
  annotations:
    kubernetes.io/change-cause: "Added logging sidecar to storage service"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: storage-service
  template:
    metadata:
      labels:
        app: storage-service
        version: "1.0.0"
        component: storage
    spec:
      containers:
      - name: storage-service
        image: storage-service:1.0.0
        ports:
        - containerPort: 8083
        env:
        - name: PORT
          value: "8083"
        volumeMounts:
        - name: log-storage
          mountPath: /app/logs
      - name: log-collector
        image: busybox:latest
        command: ['sh', '-c', 'tail -f /logs/storage-service.log']
        volumeMounts:
        - name: log-storage
          mountPath: /logs
      volumes:
      - name: log-storage
        emptyDir: {}
      # Extended grace period for data consistency
      terminationGracePeriodSeconds: 180
