apiVersion: v1
kind: ResourceQuota
metadata:
  name: avakart-quota
  namespace: avakart
spec:
  hard:
    # Compute resource limits
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    
    # Object count limits
    pods: "20"
    services: "10"
    configmaps: "10"
    secrets: "10"
    persistentvolumeclaims: "5"
