apiVersion: v1
kind: ResourceQuota
metadata:
  name: frontend-quota
  namespace: avakart
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "5"
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values: ["frontend"]
