apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: storage-manager-binding
  labels:
    app: storage-service
    app.kubernetes.io/part-of: avakart
subjects:
- kind: ServiceAccount
  name: storage-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: storage-manager
  apiGroup: rbac.authorization.k8s.io
