apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-data-restored-pvc
spec:
  dataSource:
    name: storage-data-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
