apiVersion: v1
kind: Pod
metadata:
  name: books-pod
  labels:
    app: books-service    # Consistent labeling for service discovery
spec:
  containers:
  - name: books-service
    image: books-service:latest
    ports:
    - containerPort: 8081   # Application port
    env:
    - name: PORT           # Environment variables for service configuration
      value: "8081"
    - name: STORAGE_SERVICE_URL     # Inter-service communication
      value: "http://storage-service:8083"
    - name: ORDER_PROCESSOR_URL
      value: "http://order-processor:8082"
