apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: frontend    # Labels are key for service discovery
spec:
  containers:
  - name: frontend
    image: frontend:latest
    ports:
    - containerPort: 80   # Port the container listens on
    env:
    - name: VITE_API_BASE_URL    # Environment variable for API connectivity
      value: "http://books-service:8081"
