apiVersion: v1
kind: Pod
metadata:
  name: order-processor-pod
  labels:
    app: order-processor    # Service identifier
spec:
  containers:
  - name: order-processor
    image: order-processor:latest
    ports:
    - containerPort: 8082   # Order processing service port
    env:
    - name: PORT
      value: "8082"
    - name: STORAGE_SERVICE_URL     # Dependency on storage service
      value: "http://storage-service:8083"
