apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
  labels:
    app: storage-service    # Service identifier for the storage component
spec:
  containers:
  - name: storage-service
    image: storage-service:latest
    ports:
    - containerPort: 8083   # Storage service port
    env:
    - name: PORT           # Service configuration
      value: "8083"
