apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: avakart
  labels:
    component: admission-control
    type: resource-quota
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
    services: "10"
    configmaps: "20"
    secrets: "20"
    persistentvolumeclaims: "10"
