apiVersion: v1
kind: ServiceAccount
metadata:
  name: books-service-account
  namespace: avakart
  labels:
    app: books-service
    component: backend
  annotations:
    description: "Service account for the Books service in AvaKart"
---
apiVersion: v1
kind: Secret
metadata:
  name: books-service-token
  namespace: avakart
  annotations:
    kubernetes.io/service-account.name: books-service-account
type: kubernetes.io/service-account-token
