apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-service-account
  namespace: avakart
  labels:
    app: storage-service
    component: backend
  annotations:
    description: "Service account for the Storage service in AvaKart"
---
apiVersion: v1
kind: Secret
metadata:
  name: storage-service-token
  namespace: avakart
  annotations:
    kubernetes.io/service-account.name: storage-service-account
type: kubernetes.io/service-account-token
