apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- pvc.yaml

commonLabels:
  app.kubernetes.io/name: storage-service
  app.kubernetes.io/part-of: bookstore-app

images:
- name: storage-service
  newName: storage-service
  newTag: latest
- name: busybox
  newName: busybox
  newTag: latest
