apiVersion: v1
kind: Service
metadata:
  name: storage-service
  labels:
    app: storage-service
spec:
  selector:
    app: storage-service
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
    name: http
  type: ClusterIP
