apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/books
- ../../base/frontend
- ../../base/order-processor
- ../../base/storage

namespace: bookstore-staging

commonLabels:
  environment: staging

patches:
- target:
    kind: Deployment
    name: books-service
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
- target:
    kind: Deployment
    name: frontend
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
- target:
    kind: Deployment
    name: order-processor
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
- target:
    kind: Deployment
    name: storage-service
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2

images:
- name: books-service
  newName: books-service
  newTag: staging
- name: frontend
  newName: frontend
  newTag: staging
- name: order-processor
  newName: order-processor
  newTag: staging
- name: storage-service
  newName: storage-service
  newTag: staging
