apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processor-deployment
  labels:
    app: order-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-processor
  template:
    metadata:
      labels:
        app: order-processor
    spec:
      containers:
      - name: order-processor
        image: order-processor:v1
        ports:
        - containerPort: 8082
        resources:
          requests:
            memory: "384Mi"
            cpu: "250m"
          limits:
            memory: "768Mi"
            cpu: "600m"
